### ISSUE TITLE
내역 화면 선택 모드 구현하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#10]
### 📌 내용
내역 화면에서 선택모드와 관련된 UI 기능 구현하기

### 🛠 ToDo
- [x] 아이템 롱클릭 시, 선택 모드로 변경
- [x] 아이템 롱클릭 시, 선택된 아이템 UI 변경
- [x] 선택 모드에서 아이템 클릭 시, 아이템 선택
- [x] 선택된 아이템의 개수가 0개가 되면, 선택모드 해제

**Comment by aurora32s** [comment]
#### [기획변경 🛠]
원래는 선택모드에서 아이템 클릭 시, 삭제 목록에 포함되도록 하였지만 테스트 도중 스크롤 시에 터치되는 아이템들도 삭제 목록에 포함되게 되어 선택 모드에서도 롱클릭을 해야 삭제 목록에 포함되도록 해두었습니다. 🤗

**Comment by aurora32s** [comment]
#### [수정 필요 사항 🛠]
- 선택모드로 전환될 때 상단 앱바가 변경되는 코드 수정 필요
