### ISSUE TITLE
수입/지출 내역 입력 화면 기본 UI 구현하기(post 화면)

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#12]
### 📌 내용
수입/지출 내역 수정/작성 화면의 기본 UI 구현하기

### 🛠 ToDo
- [x] 수입/지출 내역 화면에서 post 화면으로 수정/작성 mode로 이동하기
- [x] 상단 탭 구현하기
- [x] 상단 탭의 back 버튼 클릭 시, 이전 화면으로 이동하기
- [x] 상단 수입/지출 탭 구현하기
- [x] 작성 모드일 경우에만 상단 수입/지출 탭 변경 가능하도록 하기
- [x] 입력 TextField들 구현하기
- [x] 일자 DatePicker로 구현하기
- [x] 결제 수단 Spinner로 구현하기
- [x] 분류 Spinner로 구현하기
- [x] 결제 수단/분류 Spinner에 '추가하기' 버튼 추가하기
- [x] 필수 데이터 입력 전까지 버튼 비활성화하기
- [x] 금액 입력 포맷팅해주기
- [x] 등록하기 버튼 클릭 시, 이전 화면으로 이동하기

**Comment by aurora32s** [comment]
#### [문제 해결 🛠]
- 버튼 비활성화 시, 색을 바꿔주기 위해 아래와 같이 구현
```kotlin
colors = 
   ButtonDefaults.buttonColors(
      backgroundColor = if (disable) Yellow50 else Yellow
   )
```
그랬더니 아래와 같이 되었습니다. 😭
<img width="455" alt="스크린샷 2022-07-30 오전 1 19 54" src="https://user-images.githubusercontent.com/22411296/181805559-6bd893d0-e4ce-4d6e-9e84-3f7c2e026bd4.png">


이를 아래와 같이 수정하였습니다.
```kotlin
colors = ButtonDefaults.buttonColors(
    backgroundColor = ColorPalette.Yellow,
    disabledBackgroundColor = ColorPalette.Yellow50
)
```
