### ISSUE TITLE
통계 화면 기본 UI 구성하기(graph 화면)

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#16]
### 📌 내용
하단 bottom navigation tab에서 통계 클릭 시 보이는 화면(graph화면)의 기본 UI 구성하기

### 🛠 ToDo
- [x] 앱 타이틀 클릭 시, 연도와 월 선택 기능 구현
- [x] 앱 상단 화살표 클릭 시, 이전/다음 달로 이동
- [x] 상단에 총 지출 금액 표시하기
- [x] 원 그래프 애니메이션으로 그리기
- [x] 원 그래프 데이터 비율에 따라 다르게 그려주기
- [x] 하단의 카테고리별 지출 금액 표시해주기

**Comment by aurora32s** [comment]
#### [고민중 🧐]
하단의 카테고리별 지출 리스트를 일반 Column으로 할까.. LazyColumn으로 할까..

**Comment by aurora32s** [comment]
#### [참고 자료 🛠 - 원형 그래프]
[Jetpack Compose Navigation Codelab](https://developer.android.com/codelabs/jetpack-compose-navigation#1)
