### ISSUE TITLE
특정 카테고리별 지출 화면 기본 UI 구성하기(detail 화면)

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#18]
### 📌 내용
graph화면에서 카테고리 클릭 시, 해당 카테고리의 최근 6개월 간의 지출 내역을 보여주는 화면
기본 UI 구성하기

### 🛠 ToDo
- [x] 상단 앱바를 구성하고, backbutton 클릭 시 이전화면으로 이동하기
- [x] 선형그래프 그리기
- [x] 선형 그래프에 데이터 바인딩하기
- [x] 하단의 일별 지출 내역 표현해주기
   -> history 화면에서 사용한 LazyColumn 그대로 사용하기

### 🔥 추가적으로 하고 싶은 것
1. 선형 그래프를 애니메이션으로 표현하기
2. history 화면의 LazyColumn 공통 코드로 합치기

**Comment by aurora32s** [comment]
#### [나중에 한번 봐보고 싶은 문서 🔥]
[Canvas draw](https://medium.com/falabellatechnology/jetpack-compose-canvas-8aee73eab393)
