### ISSUE TITLE
설정 화면 기본 UI 구성하기(setting 화면)

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#20]
### 📌 내용
결제 수단과 지출/수입 카테고리 관리 화면 기본 UI 구현하기

### 🛠 ToDo
- [x] 결제수단 리스트 그리기
- [x] 카테고리 리스트 그리기
- [x] 결제 수단 리스트에 데이터 바인딩하기
- [x] 카테고리 리스트에 수입/지출 카테고리 데이터 바인딩하기
- [x] 결제 수단 추가 버튼 누르면 결제 수단 추가 화면으로 이동하기
- [x] 카테고리 추가 버튼 누르면 카테고리 추가 화면으로 이동하기

##### 결제 수단 추가 화면
- [x] 상단 앱바 구성하기
- [x] 상단 앱바 버튼 클릭 시, 이전 화면으로 이동하기
- [x] 결제 수단 이름 입력란 만들기
- [x] 결제 수단 이름 입력 전까지 버튼 비활성화 하기
- [x] 등록하기 버튼 클릭 시, 이전 화면으로 이동하기

##### 카테고리 추가 화면
- [x] 상단 앱바 구성하기
- [x] 상단 앱바 버튼 클릭 시, 이전 화면으로 이동하기
- [x] 카테고리 이름 입력란 만들기
- [x] 카테고리 이름 입력 전까지 버튼 비활성화 하기
- [x] 등록하기 버튼 클릭 시, 이전 화면으로 이동하기
- [x] 색상 리스트 만들기
- [x] 선택된 색상은 크게 만들어주기(애니메이션 사용)

### 🔥 추가적으로 하고 싶은 것
1. 결제 수단 추가 화면과 카테고리 추가 화면의 중복되는 기능들 코드 합치기
2. 이름 유효성 검사 조건 추가하기
3. 키보드 입력할 때 화면 줄여주기
