### ISSUE TITLE
설정 화면 DataLayer단 구성하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#25]
### 📌 내용
설정 화면의 결제수단 / 지출 카테고리 / 수입 카테고리  CRUD Datalayer단 구성하기

### 🛠 ToDo
- [x] 새로운 결제 수단 추가하기
- [x] 지출 카테고리 추가하기
- [x] 수입 카테고리 추가하기
- [x] 기존의 결제 수단 변경하기
- [x] 기존의 지출 카테고리 변경하기
- [x] 기존의 수입 카테고리 변경하기
- [x] 추가된 결제 수단 리스트로 보여주기
- [x] 추가된 지출 카테고리 리스트로 보여주기
- [x] 추가된 수입 카테고리 리스트로 보여주기
