### ISSUE TITLE
내역 화면(history 화면) DataLayer 단 구성하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#27]
### 📌 내용
내역 화면의 RD Datalayer단 구성하기

### 🛠 ToDo
- [x] 월별 수입/지출 내역 가지고 오기
- [x] 월 변경 시 수입/지출 내역 가지고 오기
- [x] 수입/지출에 따라 해당하는 내역 보여주기
- [x] 수입/지출 탭 내용 변경하기
   - [x] 수입일 때는 일별 수입 총 내용만 보여주기
   - [x] 지출일 때는 일별 지출 총 내용만 보여주기
   - [x] 수입/지출이 모두 체크되어 있다면 일별 수입/지출 총 내용 모두 보여주기
- [x] 수입/지출 내역 삭제 기능 구현하기
- [ ] 수입/지출 내역 추가 후, 내역 화면으로 돌아오면 데이터 재호출하기
