### ISSUE TITLE
통계 화면(graph 화면) Database와 연동하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#31]
### 📌 내용
통계 화면의 그래프를 위한 데이터를 Database에서 받아오기

### 🛠 ToDo
- [x] 해당 월의 카테고리 별 지출 내역 데이터 받아오는 로직 구현하기
- [x] 해당 정보 화면에 표시하기
- [x] 월 이동 시, 해당 월의 카테고리별 데이터 잘 받아오는지 확인하기
