### ISSUE TITLE
상세 화면(detail 화면) Database와 연동하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#33]
### 📌 내용
상세 화면의 그래프를 위한 데이터를 Database에서 받아와 화면에 보여주기
- 최근 6개월 간 특정 카테고리의 지출 내역

### 🛠 ToDo
- [x] 사용자가 요청한 월 이전 6개월 이내의 지출 데이터 요청
- [x] 받아온 데이터를 선형 그래프로 보여주기
- [x] 받아온 데이터를 일별 내역 리스트로 보여주기
