### ISSUE TITLE
내역 화면 기본 UI 구현하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_accountbook_12#6]
### 📌 내용
내역 화면의 기본 UI 구현하기
(UI 동작 제외)
(선택 모드 제외)

### 🛠 ToDo
- [x] 내역 화면 기본 UI 기획하기
- [x] 상단 탭 구현하기
- [x] 수입/지출 tab 구현하기
- [ ] 수입/지출 tab에 애니메이션 적용하기
- [x] 수입/지출 내역 아이템 구현하기
- [x] 수입/지출 내역 리스트로 구현하기
- [x] 내역 화면 데이터 구조 기획하기
- [x] 위에서 기획한 데이터 구조를 기반으로 mock 데이터로 화면 그리기
